config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#home'
  get('/about', { to: 'welcome#about', as: :about })
  get('/contact_us', { to: 'welcome#contact_us', as: :contact })
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )
  
  get('/home', to: 'welcome#home')
  
  
  post('/thank_you', to: 'welcome#thank_you')

  #bill splitter
  get "/bill_splitter", to: "bill_splitter#new"
  post "/calculate_split", to: "bill_splitter#create"

  # Session Routes
  resource :session, only: [:new, :create, :destroy]

  # RESTful Product Routes
  #  get '/products/new', to: 'products#new', as: :new_product
  #  post '/products', to: 'products#create'
  #  get '/products/:id', to: 'products#show', as: :product
  #  get '/products', to: 'products#index'
  #  delete '/products/:id', to: 'products#destroy'
  #  get '/products/:id/edit', to: 'products#edit', as: :edit_product
  #  patch '/products/:id', to: 'products#update'

  resources :products do
    resources :reviews, shallow: :true, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end

  resources :news_articles
  resources :favourites, only: [:index]

  resources :users, only: [:new, :create]

  namespace :admin do 
    resources :dashboard, only: [:index]
  end


  resources :users, only: [:new, :create]

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  resources :news_articles

  # API routes

  # The namespace method in Rails routes makes it so that
  # your app will automatically look in a directory api,
  # then in a sub directory v1 for QuestionsController

  # The option 'defaults: { format: :json }' will set 'json' as
  # the default response format for all routes contained within
  # the block.

  # The option 'defaults: { format: :json }' will set 'json' as
  # the default response format for all routes contained within
  # the block.

  namespace :api, defaults: { format: :json } do #👈🏻 we can set default response format of the block
    namespace :v1 do
      resources :products, only:[:index,:show,:create, :destroy]
      resource :session, only:[:create, :destroy]
      resources :users, only: [:create] do
        # get :current -> /api/v1/users/:user_id/current
        get :current, on: :collection # -> /api/v1/users/current
      end
    end
    match "*unmatched_route", to: "application#not_found", via: :all
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # A constant is a value that should never change. We use these often to replace hard coded values. That way you can use this constant in multiple areas and if you ever need to change it you'd only need to change it at one place.
  DEFAULT_PRICE = 1 # a ruby convention is to place constants at the top of the file and name them using SCREAMING_SNAKE_CASE
  # rubocop has good guidelines on best practices https://github.com/rubocop-hq/ruby-style-guide

  before_validation :set_default_price
  before_save :capitalize_title

  validates :title, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 10 }

  belongs_to :user
  # has_many accepts a scope as a second argument. This scope will make all associated reviews ordered by their updated_at, see the following example:
=begin
  @product = Product.find(params[:id])
  @product.reviews # will be all the associated reviews for this particular product and due to the scope they're all ordered by updated_at
=end

  has_many :reviews, -> { order('updated_at DESC') }, dependent: :destroy 

  # scope(name, body, &block) is a method that will add a class method for retrieving records
  # https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope
  # in ruby & rails docks &block means the method accepts a lambda.
  scope(:search, -> (query) { where("title ILIKE?", "%#{query}%") })

  # you can create a class method that does the same thing.

  def self.search_but_using_class_method(query)
    where("title ILIKE?", "%#{query}%")
  end

  def increment_hit_count
    new_hit_count = self.hit_count += 1
    update({ hit_count: new_hit_count })
  end

  def self.get_paginated(search, sort_by_col, current_page, per_page_count)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%").order(Hash[sort_by_col, :desc]).limit(per_page_count).offset(current_page * per_page_count) 
  end

  def tag_names
    self.tags.map(&:name).join(", ")
  end

  # Appending = at the end of a method name, allows to implement
  # a "setter". A setter is a method that is assignable.
  # Example:
  # p.tag_names = "stuff,yo"
  # The code in the example above would call the method we wrote
  # below where the value on the right-hand side of the = would
  # become the argument to the method.
  # This is similar to implementing an `attr_writer`.
  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  private

  def set_default_price
    self.price ||= DEFAULT_PRICE
  end

  def capitalize_title
    self.title.capitalize!
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:update, :destroy]

    before_action :find_product,only:[:show, :destroy, :update]
    
    def index
        products=Product.order(created_at: :desc)
        render(json: products, each_serializer: ProductCollectionSerializer)    
    end

    def show
        if @product
            render json: @product
        else
            render(json: { status: 404 }, status: 404)
        end
    end

    def create
        product= Product.new product_params
        product.user = current_user
        product.save!
        render json: {id: product.id }
    end

    def update
        if product.update product_params
          render json: { id: product.id }
        else
          render(
            json: { errors: product.errors },
            status: 422 # Unprocessable Entity
          )
        end
      end
    
    def destroy
        product.destroy
        render(json: { status: 200 }, status: 200)
    end

    private

    def find_product
        @product||=Product.find params[:id]
    end

    def product_params
        params.require(:product).permit(:title, :description, :price, :created_at, :reviews)
    end

    def authorize!
        render(json: { status: 401 }, status: 401) unless can? :crud, product
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_product!, except: [:create]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
  
    if params[:tag]

      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @products = @tag.products.order(created_at: :DESC)
    else
      @products = Product.order(created_at: :DESC)
    end
  end

  def new
  end

  def create
    # strong parameters are used primarily as a security practice to help
    # prevent accidentally allowing users to update sensitive model attributes.
 
    @product = Product.new product_params
    @product.user = @current_user
    if @product.save
      # ProductMailer.notify_product_owner(@product).deliver_now
      ProductMailer.notify_product_owner(@product).deliver_later
      # Eventually we will redirect to the show page for the product created
      # render plain: "Product Created"
      # instead of the above line we will use :
      redirect_to @product
      # same as redirect_to product_path(@product)
      
      
    else
      # render will simply render the new.html.erb view in the views/products
      # directory. The #new action above will not be touched.
      render :new
    end
  end

  # def index
  #   # @products = Product.all
  #   @products = Product.order(created_at: :DESC)
  # end

  def show
    @review = Review.new
    @favourite = @product.favourites.find_by_user_id current_user if user_signed_in?
  end

  def edit
  end

  def update
    # product_params = params.require(:product).permit(:title, :description, :price )
    @product = Product.find params[:id]
    if @product.update product_params
      redirect_to product_path(@product)
    else
      render :edit
    end
  end
  def destroy
    @product.destroy
    redirect_to products_path
   end

   private
   def authorize_user!
    unless can? :crud, @product
      flash[:danger] = "Acess Denied"
      redirect_to root_path
    end
   end
  

  def product_params
    # docs about params.require() https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-require
    # docs about .permit() https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-permit
    params.require(:product).permit(:title, :description, :price, :tag_names)
  end

   def load_product!
    # params_tag= params[:tag]
    if params[:id].present?
      @product = Product.find(params[:id])
    else
      @product = Product.new
    end
   end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.present? %>
  <p>
    <%= @product.errors.full_messages.join(', ')%>
  </p>
<% end %>

<%# by default rails forms will submit using XHR/AJAX we'll learn this in the future but for now we want to submit using HTML5 forms so we'll have to set the `local` option to true%>
<%# https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with %>
<%# form_with uses @product.new_record? to determine if this form should patch or post %>
<%= form_with model: @product, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control', placeholder: 'Product Name')%>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area(:description, class: 'form-control', cols: 50, rows: 5, placeholder: 'Provide Description')%>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <%= f.number_field(:price, class: 'form-control', min: 0, placeholder: 'Enter Price', step: :any )%>
  </div>
  <div class='form-group'>
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <% if @product.new_record? %>
    <%= f.submit("Create", class: 'btn btn-primary') %>
  <% else %>
    <%= f.submit("Update", class: 'btn btn-primary') %>
  <% end %>
<% end %>
<script>
  $(function(){
    $('#product_tag_names').selectize({
      delimeter: ',',
      persist: false,
      labelField: 'name',
      valueField: 'name',
      searchField: 'name',
      options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
      // The above line selects only names from tags table and converts them to
      // a json array of objects
      // without including ids and makes sure its a safe_html string
      // options: [{"name": "first tag"}, {"name": "second tag"}, {"name": "third tag"},
      //           {"name": "fourth tag"}, {"name": "fifth tag"}, ...]
      create: function(input) {
        return {
            name: input 
        }
      }
    });
  });
</script> 

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render 'form'  %> 

app/views/products/index.html.erb
<div class='row'>
  <div class='col-2'>
    <% if @tag.present? %>
      <h6>
        Showing products tagged by:
        <span class="badge badge-pill badge-primary">
          <%= @tag.name %>
        </span>
      </h6>
    <% end %>
  </div>

  <div class='col-10'>
    <div class='list-group'>
      <% @products.each do |product| %>
        <%= link_to product do %>
          <li class='list-group-item'>
            <p><span class='badge badge-light'><%= product.id %></span> <%= product.title %></p>
            <small>Last Updated: <%= time_ago_in_words product.updated_at %></small>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>
</div> 

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded overflow-wrap'>
  <div class='clearfix'>
    <h1 class='float-left'>
      <span class='badge badge-pill badge-info'>
        <%= @product.id %>
      </span>
      <%= @product.title %>
    </h1>
    <h1 class='float-right text-center'>
      <%# if @product.sale_price.present? && @product.sale_price < @product.price %>
        <span class='badge badge-pill badge-success'><s><%#= number_to_currency @product.price %></s></span>
        <span class='badge badge-pill badge-danger'><%#=# number_to_currency @product.sale_price %></span>
      <%# else %>
        <span class='badge badge-pill badge-success'><%= number_to_currency @product.price %></span>
      <%# end %>
    </h1>
    
  </div>
  <small class='text-muted'>
    sold by <em><%= @product.user.full_name %></em>
  <small>
  <hr/>
  <p class='shadow-none p-3 rounded'><%= @product.description %></p>
  <p>Tags:</p>
  <% unless @product.tags.empty? %>
    <div>
      <% @product.tags.each do |tag| %>
        <%= link_to(
            tag.name,
            products_path(tag: tag.name), class: "badge badge-pill badge-primary"
        ) %>
      <% end %>
    </div>
  <% end %>
  <div>
    <%# link_to() just creates a anchor tag with the appropriate href. The 3rd argument is a optional options hash which can have a :method key; If a :method key is provided Rails will set a data-method attribute to the a tag and adds some additional javascript to the page which makes the anchor tag use the specified http method instead of the default GET. (Basically Rails Magic) 
    <%# https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to %>
    <%# passing a value (number/string) to a helper method like `product_path` will return a path with the value appended to the path. Helper paths automatically grab and use the id if it's given a instance %>
    <%= link_to(
      "Delete",
      product_path(@product),
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'are you sure?' },
      )
    %>
    <%= link_to "Edit", edit_product_path(@product), class: 'btn btn-info'%>
    |
    <% if user_signed_in? && can?(:favourite, @product) %>
      <% if @favourite.present? %>
        <%= link_to 'Un Fav', favourite_path(@favourite), method: :delete %>
      <% else %>
        <%= link_to 'Fav', product_favourites_path(@product), method: :post %>
      <% end %>
    <% end %>
  </div>
</div> 
<p class='text-muted'>Leave a Review :D</p>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: [@product, @review], local: true do |f| %>
    <div class='form-group'>
      <%= f.label :rating %>
      <%= f.select(:rating, options_for_select(1..5), class: 'form-control' )%>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.text_area(:body, class: 'form-control', placeholder: 'Your thoughts here' )%>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

<h2> Here's what people are saying: </h2>

<% @product.reviews.each do |review| %>
  <div class='shadow-sm p-3 mb-1 bg-white rounded'>   
  <%# display_stars is a custom helper method to display stars located in /app/helpers/reviews_helper.rb %>
  <%# all methods defined in any helper file are available in all views :D. We can place complex logic in these helpers to avoid bloating our model. (business logic inside of controller should be kept to a minimum) %>
    <h4>
      <%= display_stars(review) %>
      <p class='font-weight-lighter d-inline-block'>by <%= review.user.full_name %></p>
      <% if user_signed_in? && can?(:like, review) %>
        <% like = current_user.likes.find_by_review_id(review) %>
        <% if like %>
          <%= link_to 'Unlike', like_path(like), method: :delete %>
        <% else %>
          <%= link_to 'Like', review_likes_path(review), method: :post %>
        <% end %>
      <% end %>
      (<%= pluralize review.likes.count, 'like' %>)

      <% vote = review.votes.find_by(user: current_user) %>
      <span class="vote-widget">
        <% if vote.nil? %>
          <%= link_to 'vote up', review_votes_path(review, is_up: true), method: :post %>
          <%= review.vote_total %>
          <%= link_to 'vote down', review_votes_path(review, is_up: false), method: :post %>
        <% elsif vote.is_up? %>
          <%= link_to 'vote up', vote_path(vote), method: :delete, class: 'active' %>
          <%= review.vote_total %>
          <%= link_to 'vote down', vote_path(vote, is_up: false), method: :patch %>
        <% else %>
          <%= link_to 'vote up', vote_path(vote, is_up: true), method: :patch %>
          <%= review.vote_total %>
          <%= link_to 'vote down', vote_path(vote), method: :delete %>
        <% end %>
      </span>
      (<%= review.vote_total %>)
      <%= link_to(
        "Delete",
        review_path(@product, review),
        method: :delete,
        class: 'btn btn-danger float-right',
        data: { confirm: 'delete this review?' }
        )
      %>
    </h4>
    <%# adding styles to .review-body inside of 'app/assets/stylesheets/reviews.scss'. Rails will automatically include stylesheets in controllers if the name of the stylesheet is the same name as the controller %>
    <p class='review-body text-muted'><%= review.body %></p>
  </div>
  <%= link_to(fa_icon('arrow-up'), review_votes_path(review, is_up: true), method: :post) %>
  
  <%= link_to(fa_icon('arrow-down'), review_votes_path(review, is_up: false), method: :post) %>

<% end %>

<%#
  
 
%>